apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-profile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-profile
  template:
    metadata:
      labels:
        app: front-profile
    spec:
      containers:
      - name: front-container
        image: jdark91/front-profile:latest
        ports:
        - containerPort: 80
