name: Deploy Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.RASPBERRY_HOST }}
        username: ${{ secrets.RASPBERRY_USER }}
        password: ${{ secrets.RASPBERRY_PASSWORD }}
        script: |
          cd /home/y0rshb3/devops/temp_frontend
          git pull origin main
          npm install
          npm run build
          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 3000:80 \
            -v /home/y0rshb3/devops/temp_frontend/dist:/usr/share/nginx/html \
            -v /home/y0rshb3/devops/temp_frontend/nginx.conf:/etc/nginx/conf.d/default.conf \
            --restart=always nginx:alpine
          echo ✅ Frontend deployed successfully!
